/*
* @Author: AlanWang
* @Date:   2017-10-09 09:27:21
* @Last Modified by:   AlanWang
* @Last Modified time: 2017-12-04 17:38:18
*/

// http communicating
export const SEND_HTTP_REQUEST = 'SEND_HTTP_REQUEST'
export const RESPONSE_SUCCESS = 'RESPONSE_SUCCESS'
export const RESPONSE_FAIL = 'RESPONSE_FAIL'

// forgetLoginPwd
export const UPDATE_PHONE = 'UPDATE_PHONE'
export const UPDATE_VERIFICATION = 'UPDATE_VERIFICATION'
export const UPDATE_RESET_PWD = 'UPDATE_RESET_PWD'
export const RESET_LOGIN_PWD_SUCCESS = 'RESET_LOGIN_PWD_SUCCESS'
export const FETCH_RESET_PWD_VERIFICATION_SUCCESS = 'FETCH_RESET_PWD_VERIFICATION_SUCCESS'
export const RESET_PWD_VERIFICATION_COOLING = 'RESET_PWD_VERIFICATION_COOLING'

// Home
export const RECEIVE_HOME_DATA = 'RECEIVE_HOME_DATA'
export const RECEIVE_REFUND_DATA = 'RECEIVE_REFUND_DATA'
export const APPLY_AGAIN = 'APPLY_AGAIN'

// Authentication Center
export const UPDATE_AUTHENTICATION_CENTER = 'UPDATE_AUTHENTICATION_CENTER'
export const UPDATE_AUTHENTICATION_CENTER_BY_NAME = 'UPDATE_AUTHENTICATION_CENTER_BY_NAME'

// /identity
export const UPDATE_AUTHENTICATION_IDENTITY = 'UPDATE_AUTHENTICATION_IDENTITY'
export const DISABLE_IDENTITY_BTN_CONFIRM = 'DISABLE_IDENTITY_BTN_CONFIRM'
export const UPDATE_IDENTITY_CONFIRM_MSG = 'UPDATE_IDENTITY_CONFIRM_MSG'
export const UPDATE_IDENTITY_NAME = 'UPDATE_IDENTITY_NAME'
export const UPDATE_IDENTITY_ICNUMBER = 'UPDATE_IDENTITY_ICNUMBER'

// /bankcard
export const RECEIVE_AUTHENTICATED_BANKCARDS = 'RECEIVE_AUTHENTICATED_BANKCARDS'
export const SET_DEFAULT_BANKCARD = 'SET_DEFAULT_BANKCARD'
export const UPDATE_ACCOUNT_NAME = 'UPDATE_ACCOUNT_NAME'
export const UPDATE_BANKCARD_NUM = 'UPDATE_BANKCARD_NUM'
export const CLEAR_BANKCARD_NUM = 'CLEAR_BANKCARD_NUM'
export const UPDATE_IDCARD_NUM = 'UPDATE_IDCARD_NUM'
export const VALIDTE_BANKCARD_NUMBER_ERROR = 'VALIDTE_BANKCARD_NUMBER_ERROR'
export const RECEIVE_ADD_BANKCARD_REQ_DATA = 'RECEIVE_ADD_BANKCARD_REQ_DATA'
export const UPDATE_ADD_BANKCARD_RESPONSE_ERR_MSG = 'UPDATE_ADD_BANKCARD_RESPONSE_ERR_MSG'

// /personalInfo
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const UPDATE_USER_INFO_ADDRESS = 'UPDATE_USER_INFO_ADDRESS'
export const UPDATE_USER_INFO_PARTICULARADDRESS = 'UPDATE_USER_INFO_PARTICULARADDRESS'
export const UPDATE_USER_INFO_TIME = 'UPDATE_USER_INFO_TIME'
export const SAVE_USER_INFO_SUCCESS = 'SAVE_USER_INFO_SUCCESS'
export const UPDATE_JOB_INFO = 'UPDATE_JOB_INFO'
export const UPDATE_JOB_INFO_INDUSTRY = 'UPDATE_JOB_INFO_INDUSTRY'
export const UPDATE_JOB_INFO_POSITION = 'UPDATE_JOB_INFO_POSITION'
export const UPDATE_JOB_INFO_COMPANY = 'UPDATE_JOB_INFO_COMPANY'
export const UPDATE_JOB_INFO_ADDRESS = 'UPDATE_JOB_INFO_ADDRESS'
export const UPDATE_JOB_INFO_PARTICULARADDRESS = 'UPDATE_JOB_INFO_PARTICULARADDRESS'
export const UPDATE_JOB_INFO_TELEPHONE = 'UPDATE_JOB_INFO_TELEPHONE'
export const SAVE_JOB_INFO_SUCCESS = 'SAVE_JOB_INFO_SUCCESS'
export const UPDATE_RELATION_INFO = 'UPDATE_RELATION_INFO'
export const UPDATE_RELATION_INFO_BY_KEY = 'UPDATE_RELATION_INFO_BY_KEY'
export const SAVE_RELATION_INFO_SUCCESS = 'SAVE_RELATION_INFO_SUCCESS'

// /upLimit
export const VALIDTE_BANKCARD_NUMBER_SUCCESS = 'VALIDTE_BANKCARD_NUMBER_SUCCESS'
export const UPDATE_AUTHENTICATE_ACC = 'UPDATE_AUTHENTICATE_ACC'
export const UPDATE_AUTHENTICATE_PWD = 'UPDATE_AUTHENTICATE_PWD'
export const UPDATE_AUTHENTICATE_TAOBAO_PHONE = 'UPDATE_AUTHENTICATE_TAOBAO_PHONE'
export const UPDATE_AUTHENTICATE_TAOBAO_VERIFICATION = 'UPDATE_AUTHENTICATE_TAOBAO_VERIFICATION'
export const UPDATE_AUTHENTICATE_JINDONG_VERIFICATION = 'UPDATE_AUTHENTICATE_JINDONG_VERIFICATION'
export const AUTHENTICATE_FOR_UP_LIMIT = 'AUTHENTICATE_FOR_UP_LIMIT'
export const RECEIVE_AUTHENTICATED = 'RECEIVE_AUTHENTICATED'
export const AUTHEN_DIPLOMA_SUCCESS = 'AUTHEN_DIPLOMA_SUCCESS'
export const TOGGLE_JINGDONG_VERIFICATION_INPUT = 'TOGGLE_JINGDONG_VERIFICATION_INPUT'
export const ALERT_JINGDONG_AUTHENTICATE_ERROR = 'ALERT_JINGDONG_AUTHENTICATE_ERROR'
export const CHANGE_JINGDONG_AUTHENTICATE = 'CHANGE_JINGDONG_AUTHENTICATE'
export const SHOW_JINGDONG_AUTHENTICATE_SUCCESS = 'SHOW_JINGDONG_AUTHENTICATE_SUCCESS'
export const CHANGE_AUTHENTICATE_TAOBAO_STATE = 'CHANGE_AUTHENTICATE_TAOBAO_STATE'
export const CHANGE_AUTHENTICATE_DIPLOMA_STATE = 'CHANGE_AUTHENTICATE_DIPLOMA_STATE'
export const CHANGE_CREDIT_BILL_STATE = 'CHANGE_CREDIT_BILL_STATE'
export const CHANGE_AUTHENTICATE_EBANK_STATE = 'CHANGE_AUTHENTICATE_EBANK_STATE'
export const RECEIVE_AUTHENTICATE_QR = 'RECEIVE_AUTHENTICATE_QR'
export const CLOSE_AUTHENTICATE_POPUP_QR = 'CLOSE_AUTHENTICATE_POPUP_QR'
export const TOGGLE_RESULT_SHOW = 'TOGGLE_RESULT_SHOW'

// Personal Center
// /record
export const RECIEVE_RECORD_LOAN_LIST = 'RECIEVE_RECORD_LOAN_LIST'
export const CLEAR_LOANS = 'CLEAR_LOANS'
export const CLEAR_REPAYMENTS = 'CLEAR_REPAYMENTS'
export const LOADED_RECORD_LOAN_FULL = 'LOADED_RECORD_LOAN_FULL'
export const UNLOADED_RECORD_LOAN_FULL = 'UNLOADED_RECORD_LOAN_FULL'
export const UPDATE_RECORD_LOAN = 'UPDATE_RECORD_LOAN'
export const RECIEVE_RECORD_REPAYMENT_LIST = 'RECIEVE_RECORD_REPAYMENT_LIST'
export const UNLOADED_RECORD_REPAYMENT_FULL = 'UNLOADED_RECORD_REPAYMENT_FULL'
export const LOADED_RECORD_REPAYMENT_FULL = 'LOADED_RECORD_REPAYMENT_FULL'
export const SHOW_LOAN_DETAIL = 'SHOW_LOAN_DETAIL'
export const HIDE_LOAN_DETAIL = 'HIDE_LOAN_DETAIL'

// /voucher
export const UPDATE_VOUCHERS = 'UPDATE_VOUCHERS'

// /feedback
export const SUBMIT_FEEDBACK_SUCCESS = 'SUBMIT_FEEDBACK_SUCCESS'
export const UPDATE_QUESTION_TYPE = 'UPDATE_QUESTION_TYPE'
export const UPDATE_QUESTION_CONTENT = 'UPDATE_QUESTION_CONTENT'
