/*
* @Author: AlanWang
* @Date:   2017-10-09 09:27:21
 * @Last modified by:
 * @Last modified time: 2018-02-02T09:43:49+08:00
*/

// http communicating
export const SEND_HTTP_REQUEST = 'SEND_HTTP_REQUEST'
export const RESPONSE_SUCCESS = 'RESPONSE_SUCCESS'
export const RESPONSE_FAIL = 'RESPONSE_FAIL'

// user
export const RECEIVE_USER_IS_AUTH_PASS = 'RECEIVE_USER_IS_AUTH_PASS'
export const RECEIVE_USER_AVAILABLE_QUOTA = 'RECEIVE_USER_AVAILABLE_QUOTA'
export const RECEIVE_USER_MAX_QUOTA = 'RECEIVE_USER_MAX_QUOTA'
export const RECEIVE_USER_MOBILE = 'RECEIVE_USER_MOBILE'
export const UPDATE_USER_QUOTA_RANGE = 'UPDATE_USER_QUOTA_RANGE'
export const UPDATE_FOR_MODIFY_PWD = 'UPDATE_FOR_MODIFY_PWD'
export const VALIDATE_FOR_MODIFY_PWD = 'VALIDATE_FOR_MODIFY_PWD'
export const MODIFY_PWD_SUCCESS = 'MODIFY_PWD_SUCCESS'
export const CLEAR_FOR_MODIFY_PWD = 'CLEAR_FOR_MODIFY_PWD'
// login
export const TOGGLE_USER_LOGIN_STATUS = 'TOGGLE_USER_LOGIN_STATUS'
export const UPDATE_FOR_LOGIN = 'UPDATE_FOR_LOGIN'
export const VALIDATE_FOR_LOGIN = 'VALIDATE_FOR_LOGIN'
export const CHECKED_VALIDATION_FOR_LOGIN = 'CHECKED_VALIDATION_FOR_LOGIN'
export const TOGGLE_VALIDATION_ERR = 'TOGGLE_VALIDATION_ERR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const CLEAR_LOGIN_INPUTS = 'CLEAR_LOGIN_INPUTS'
// resetPwd
export const UPDATE_FOR_RESET_PWD = 'UPDATE_FOR_RESET_PWD'
export const VALIDATE_RESET_PWD = 'VALIDATE_RESET_PWD'
export const RESET_LOGIN_PWD_SUCCESS = 'RESET_LOGIN_PWD_SUCCESS'
export const FETCH_RESET_PWD_VERIFICATION_SUCCESS = 'FETCH_RESET_PWD_VERIFICATION_SUCCESS'
export const RESET_PWD_VERIFICATION_COOLING = 'RESET_PWD_VERIFICATION_COOLING'
export const CLEAR_FOR_RESET_PWD = 'CLEAR_FOR_RESET_PWD'
// register
export const UPDATE_INPUT_FOR_REGISTER = 'UPDATE_INPUT_FOR_REGISTER'
export const VALIDATE_REGISTER = 'VALIDATE_REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const FETCH_REGISTER_VERIFICATION_SUCCESS = 'FETCH_REGISTER_VERIFICATION_SUCCESS'
export const REGISTER_VERIFICATION_COOLING = 'REGISTER_VERIFICATION_COOLING'
export const CHECK_REGISTER_PROTOCOL = 'CHECK_REGISTER_PROTOCOL'
export const CLEAR_TIME_ID_FOR_REGISTER = 'CLEAR_TIME_ID_FOR_REGISTER'

// container
export const TOGGLE_TABBAR_SHOW = 'TOGGLE_TABBAR_SHOW'
// home
// cash
export const UPDATE_FOR_CASH = 'UPDATE_FOR_CASH'
export const RECEIVE_CASH_USE_AND_PERIOD = 'RECEIVE_CASH_USE_AND_PERIOD'
export const RECEIVE_RATE = 'RECEIVE_RATE'
export const RECEIVE_USER_USE_BANKCARD = 'RECEIVE_USER_USE_BANKCARD'
// consume
export const UPDATE_SHOP_NO = 'UPDATE_SHOP_NO'
export const CHECK_SHOP_NO = 'CHECK_SHOP_NO'
export const RECEIVE_SHOP_BASE_INFO = 'RECEIVE_SHOP_BASE_INFO'
export const RECEIVE_SHOP_FOR_CONSUME = 'RECEIVE_SHOP_FOR_CONSUME'
export const RECEIVE_SHOP_PRODUCT_CATE = 'RECEIVE_SHOP_PRODUCT_CATE'
// shop
export const RECEIVE_PRODUCTS_BY_DEFINED_CATE_ID = 'RECEIVE_PRODUCTS_BY_DEFINED_CATE_ID'
export const CHANGE_CURRENT_PRODUCT_CATE = 'CHANGE_CURRENT_PRODUCT_CATE'
export const UPDATE_PRODUCT_ID = 'UPDATE_PRODUCT_ID'
export const RECEIVE_PRODUCT_DETAIL = 'RECEIVE_PRODUCT_DETAIL'
export const UPDATE_FOR_PRODUCT_IN_CONSUME = 'UPDATE_FOR_PRODUCT_IN_CONSUME'
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const EMPTY_CART = 'EMPTY_CART'
export const CHANGE_PRODUCT_COUNT_IN_SHOP_CART = 'CHANGE_PRODUCT_COUNT_IN_SHOP_CART'
export const RECEIVE_PRODUCT_AMOUNT = 'RECEIVE_PRODUCT_AMOUNT'
export const SUBMIT_LOAN_SUCCESS = 'SUBMIT_LOAN_SUCCESS'
export const CLEAR_SHOP_DATA_FOR_CONSUME = 'CLEAR_SHOP_DATA_FOR_CONSUME'
// personal photo
export const UPDATE_FOR_PERSONAL_PHOTO = 'UPDATE_FOR_PERSONAL_PHOTO'
export const RECEIVE_PERSONAL_PHOTO = 'RECEIVE_PERSONAL_PHOTO'
export const OPERATE_PERSONAL_PHOTO_MSG = 'OPERATE_PERSONAL_PHOTO_MSG'
export const SELECTED_PERSONAL_PHOTO = 'SELECTED_PERSONAL_PHOTO'
export const TOGGLE_PHOTO_CONFIRMED = 'TOGGLE_PHOTO_CONFIRMED' // switch for triggering times order submit, used by 'watch' feature

// mall
export const RECEIVE_SHOPS_LIST = 'RECEIVE_SHOPS_LIST'
export const LOAD_MORE_FOR_SHOPS = 'LOAD_MORE_FOR_SHOPS'
export const UPDATE_FOR_SHOPS_IN_MALL = 'UPDATE_FOR_SHOPS_IN_MALL'
export const RECEIVE_SHOP_DETAIL_IN_MALL = 'RECEIVE_SHOP_DETAIL_IN_MALL'
export const CLEAR_SEARCH = 'CLEAR_SEARCH'
// me
// shop
export const UPDATE_FOR_SHOP = 'UPDATE_FOR_SHOP'
export const SUBMIT_SHOP_SUCCESS = 'SUBMIT_SHOP_SUCCESS'
// refund
export const INIT_DATA_FOR_LENDS_IN_REFUND = 'INIT_DATA_FOR_LENDS_IN_REFUND'
export const RECEIVE_LEND_RECORDS = 'RECEIVE_LEND_RECORDS'
export const RECEIVE_LATEST_MONTHLY_REPAYING = 'RECEIVE_LATEST_MONTHLY_REPAYING'
export const RECEIVE_LEND_RECORD_DETAIL = 'RECEIVE_LEND_RECORD_DETAIL'
export const RECEIVE_LEND_RECORDS_SETTLE = 'RECEIVE_LEND_RECORDS_SETTLE'
export const RECEIVE_SETTLE_DATA = 'RECEIVE_SETTLE_DATA'
export const RECEIVE_IMDIATE_DATA = 'RECEIVE_IMDIATE_DATA'
// lend
// lends
export const RECEIVE_LENDS_RECORD = 'RECEIVE_LENDS_RECORD'
export const UPDATE_MSG_FOR_LENDS = 'UPDATE_MSG_FOR_LENDS'
export const INIT_DATA_FOR_LENDS = 'INIT_DATA_FOR_LENDS'
export const RECEIVE_LENDS_DETAIL = 'RECEIVE_LENDS_DETAIL'
export const RECEIVE_LENDS_LOGS = 'RECEIVE_LENDS_LOGS'
export const RECEIVE_LENDS_PLAN = 'RECEIVE_LENDS_PLAN'
export const UPDATE_LOAN_ID_FOR_LENDS = 'UPDATE_LOAN_ID_FOR_LENDS'

// refunds
export const RECEIVE_REFUNDS_DATA = 'RECEIVE_REFUNDS_DATA'
export const INIT_DATA_FOR_REFUNDS = 'INIT_DATA_FOR_REFUNDS'

// Home
export const RECEIVE_HOME_DATA = 'RECEIVE_HOME_DATA'
export const RECEIVE_REFUND_DATA = 'RECEIVE_REFUND_DATA'
export const APPLY_AGAIN = 'APPLY_AGAIN'

// Authentication Center
export const UPDATE_AUTHENTICATION_CENTER = 'UPDATE_AUTHENTICATION_CENTER'
export const UPDATE_AUTHENTICATION_CENTER_BY_NAME = 'UPDATE_AUTHENTICATION_CENTER_BY_NAME'

// /identity
export const UPDATE_AUTHENTICATION_IDENTITY = 'UPDATE_AUTHENTICATION_IDENTITY'
export const DISABLE_IDENTITY_BTN_CONFIRM = 'DISABLE_IDENTITY_BTN_CONFIRM'
export const UPDATE_IDENTITY_CONFIRM_MSG = 'UPDATE_IDENTITY_CONFIRM_MSG'
export const UPDATE_IDENTITY_NAME = 'UPDATE_IDENTITY_NAME'
export const UPDATE_IDENTITY_ICNUMBER = 'UPDATE_IDENTITY_ICNUMBER'

// /bankcard
export const RECEIVE_AUTHENTICATED_BANKCARDS = 'RECEIVE_AUTHENTICATED_BANKCARDS'
export const SET_DEFAULT_BANKCARD = 'SET_DEFAULT_BANKCARD'
export const UPDATE_ACCOUNT_NAME = 'UPDATE_ACCOUNT_NAME'
export const UPDATE_BANKCARD_NUM = 'UPDATE_BANKCARD_NUM'
export const CLEAR_BANKCARD_NUM = 'CLEAR_BANKCARD_NUM'
export const UPDATE_IDCARD_NUM = 'UPDATE_IDCARD_NUM'
export const VALIDTE_BANKCARD_NUMBER_ERROR = 'VALIDTE_BANKCARD_NUMBER_ERROR'
export const RECEIVE_ADD_BANKCARD_REQ_DATA = 'RECEIVE_ADD_BANKCARD_REQ_DATA'
export const UPDATE_ADD_BANKCARD_RESPONSE_ERR_MSG = 'UPDATE_ADD_BANKCARD_RESPONSE_ERR_MSG'

// /personalInfo
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const UPDATE_USER_INFO_ADDRESS = 'UPDATE_USER_INFO_ADDRESS'
export const UPDATE_USER_INFO_PARTICULARADDRESS = 'UPDATE_USER_INFO_PARTICULARADDRESS'
export const UPDATE_USER_INFO_TIME = 'UPDATE_USER_INFO_TIME'
export const SAVE_USER_INFO_SUCCESS = 'SAVE_USER_INFO_SUCCESS'
export const UPDATE_JOB_INFO = 'UPDATE_JOB_INFO'
export const UPDATE_JOB_INFO_INDUSTRY = 'UPDATE_JOB_INFO_INDUSTRY'
export const UPDATE_JOB_INFO_POSITION = 'UPDATE_JOB_INFO_POSITION'
export const UPDATE_JOB_INFO_COMPANY = 'UPDATE_JOB_INFO_COMPANY'
export const UPDATE_JOB_INFO_ADDRESS = 'UPDATE_JOB_INFO_ADDRESS'
export const UPDATE_JOB_INFO_PARTICULARADDRESS = 'UPDATE_JOB_INFO_PARTICULARADDRESS'
export const UPDATE_JOB_INFO_TELEPHONE = 'UPDATE_JOB_INFO_TELEPHONE'
export const SAVE_JOB_INFO_SUCCESS = 'SAVE_JOB_INFO_SUCCESS'
export const UPDATE_RELATION_INFO = 'UPDATE_RELATION_INFO'
export const UPDATE_RELATION_INFO_BY_KEY = 'UPDATE_RELATION_INFO_BY_KEY'
export const SAVE_RELATION_INFO_SUCCESS = 'SAVE_RELATION_INFO_SUCCESS'

// /upLimit
export const VALIDTE_BANKCARD_NUMBER_SUCCESS = 'VALIDTE_BANKCARD_NUMBER_SUCCESS'
export const UPDATE_AUTHENTICATE_ACC = 'UPDATE_AUTHENTICATE_ACC'
export const UPDATE_AUTHENTICATE_PWD = 'UPDATE_AUTHENTICATE_PWD'
export const UPDATE_AUTHENTICATE_TAOBAO_PHONE = 'UPDATE_AUTHENTICATE_TAOBAO_PHONE'
export const UPDATE_AUTHENTICATE_TAOBAO_VERIFICATION = 'UPDATE_AUTHENTICATE_TAOBAO_VERIFICATION'
export const UPDATE_AUTHENTICATE_JINDONG_VERIFICATION = 'UPDATE_AUTHENTICATE_JINDONG_VERIFICATION'
export const AUTHENTICATE_FOR_UP_LIMIT = 'AUTHENTICATE_FOR_UP_LIMIT'
export const RECEIVE_AUTHENTICATED = 'RECEIVE_AUTHENTICATED'
export const CHANGE_AUTHENTICATE_CREDIT_STATE = 'CHANGE_AUTHENTICATE_CREDIT_STATE'
export const UPDATE_AUTHENTICATE_CREDIT_IDENTITY_CODE = 'UPDATE_AUTHENTICATE_CREDIT_IDENTITY_CODE'
export const UPDATE_SELECTED_CITY = 'UPDATE_SELECTED_CITY'
export const CHANGE_AUTHENTICATE_HOUSEFUND_STATE = 'CHANGE_AUTHENTICATE_HOUSEFUND_STATE'
export const CHANGE_AUTHENTICATE_SOCIAL_STATE = 'CHANGE_AUTHENTICATE_SOCIAL_STATE'
export const AUTHEN_DIPLOMA_SUCCESS = 'AUTHEN_DIPLOMA_SUCCESS'
export const TOGGLE_JINGDONG_VERIFICATION_INPUT = 'TOGGLE_JINGDONG_VERIFICATION_INPUT'
export const ALERT_JINGDONG_AUTHENTICATE_ERROR = 'ALERT_JINGDONG_AUTHENTICATE_ERROR'
export const CHANGE_JINGDONG_AUTHENTICATE = 'CHANGE_JINGDONG_AUTHENTICATE'
export const SHOW_JINGDONG_AUTHENTICATE_SUCCESS = 'SHOW_JINGDONG_AUTHENTICATE_SUCCESS'
export const CHANGE_AUTHENTICATE_TAOBAO_STATE = 'CHANGE_AUTHENTICATE_TAOBAO_STATE'
export const CHANGE_AUTHENTICATE_DIPLOMA_STATE = 'CHANGE_AUTHENTICATE_DIPLOMA_STATE'
export const CHANGE_CREDIT_BILL_STATE = 'CHANGE_CREDIT_BILL_STATE'
export const CHANGE_AUTHENTICATE_EBANK_STATE = 'CHANGE_AUTHENTICATE_EBANK_STATE'
export const RECEIVE_AUTHENTICATE_QR = 'RECEIVE_AUTHENTICATE_QR'
export const CLOSE_AUTHENTICATE_POPUP_QR = 'CLOSE_AUTHENTICATE_POPUP_QR'
export const TOGGLE_RESULT_SHOW = 'TOGGLE_RESULT_SHOW'

// Personal Center
// /record
export const RECIEVE_RECORD_LOAN_LIST = 'RECIEVE_RECORD_LOAN_LIST'
export const CLEAR_LOANS = 'CLEAR_LOANS'
export const CLEAR_REPAYMENTS = 'CLEAR_REPAYMENTS'
export const LOADED_RECORD_LOAN_FULL = 'LOADED_RECORD_LOAN_FULL'
export const UNLOADED_RECORD_LOAN_FULL = 'UNLOADED_RECORD_LOAN_FULL'
export const UPDATE_RECORD_LOAN = 'UPDATE_RECORD_LOAN'
export const RECIEVE_RECORD_REPAYMENT_LIST = 'RECIEVE_RECORD_REPAYMENT_LIST'
export const UNLOADED_RECORD_REPAYMENT_FULL = 'UNLOADED_RECORD_REPAYMENT_FULL'
export const LOADED_RECORD_REPAYMENT_FULL = 'LOADED_RECORD_REPAYMENT_FULL'
export const SHOW_LOAN_DETAIL = 'SHOW_LOAN_DETAIL'
export const HIDE_LOAN_DETAIL = 'HIDE_LOAN_DETAIL'

// /voucher
export const UPDATE_VOUCHERS = 'UPDATE_VOUCHERS'

// /feedback
export const SUBMIT_FEEDBACK_SUCCESS = 'SUBMIT_FEEDBACK_SUCCESS'
export const UPDATE_QUESTION_TYPE = 'UPDATE_QUESTION_TYPE'
export const UPDATE_QUESTION_CONTENT = 'UPDATE_QUESTION_CONTENT'
